### ISSUE TITLE
Want to collaborate?

### ISSUE THREAD

**Issue by kaushalmodi** [yglukhov/emacs#1]
Hello,

I just discovered link to this repo on the Nim IRC/Gitter. I played with Nim for creating Emacs modules a while back: https://github.com/kaushalmodi/nim-emacs-module (it's a fork off https://github.com/yuutayamada/nim-emacs-module .. may be the original developer is not interested in merging my PR's.. so I just kept on committing to the master branch of my fork).

Do you want to add your work to https://github.com/kaushalmodi/nim-emacs-module ? I can move that repo to an organization if the original author @yuutayamada is fine with that.

---

- [Quick example][1]
- [Test suite of elisp calls to Nim compiled procs][2]
  - [Source code of those called Nim procs][3]

[1]: https://github.com/kaushalmodi/nim-emacs-module#another-example
[2]: https://github.com/kaushalmodi/nim-emacs-module/blob/master/test/test-modtest.el
[3]: https://github.com/kaushalmodi/nim-emacs-module/blob/master/test/modtest2.nim

**Comment by yuutayamada** [comment]
Hi Kaushal,

Sorry not replying to your PR. I am fine whatever you do in your fork.

**Comment by yglukhov** [comment]
Wow, I didn't know it existed. Damn, it's so hard to become a pioneer nowadays :).

Thanks for the invitation, though I'm not sure if that's gonna work. This one i'm doing just for fun, in my own opinionated way, and can break it as much as I want. Both projects seem to do roughly the same, but in slightly different styles, and I'm obviously biased towards my style, especially now that I've put some effort into it. :) Who knows, I might not even start it if I knew about your project before.
